@id=ea19514d-e23c-44f4-bb1c-1ad5a8094609

PUT  http://localhost:5185/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Meat Sandwich",
    "description": "Meat Meat Meat I want MEAT!",
    "startDateTime": "2023-04-08T08:00:00",
    "endDateTime": "2023-04-08T11:00:00",
    "savory": [
        "Bacon",
        "Ham",
        "RibEye",
        "Salami"
    ],
    "Sweet": [
        "Lemonade"
    ]
}