@id=c2d3a286-9cec-443e-b29e-54bcbcea3ec6

PUT  http://localhost:5185/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Meat Sandwich",
    "description": "Meat Meat Meat Meat Meat Meat Meat Meat Meat I want MEAT!",
    "startDateTime": "2023-04-08T08:00:00",
    "endDateTime": "2023-04-08T11:00:00",
    "savory": [
        "Bacon",
        "Ham",
        "RibEye",
        "Salami"
    ],
    "Sweet": [
        "Lemonade"
    ]
}