@id=f03cd4cc-c5aa-4134-8a06-3e4977133604

PUT  http://localhost:5185/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Meat Sandwich",
    "description": "Meat Meat Meat I want MEAT!",
    "startDateTime": "2023-04-08T08:00:00",
    "endDateTime": "2023-04-08T11:00:00",
    "savory": [
        "Bacon",
        "Ham",
        "RibEye",
        "Salami"
    ],
    "Sweet": [
        "Lemonade"
    ]
}